"""JSON Schemas for the rule configuration, generated from the rule registry
(P3-D2 AC: "each [rule] with a JSON-schema for its params") — pure.

Two views of the same truth, both derived from each rule's `Params` model so
they can never drift from what the engine actually accepts:

* `rule_param_schemas()` — one schema per rule id, for its `params`;
* `rules_file_schema()` — a schema for the whole `config/rules.yaml`, so editors
  (e.g. the YAML language server) can validate and autocomplete it, and a future
  rule-editor UI can render forms from it.
"""

from __future__ import annotations

from typing import Any

from events.domain.rules import Rule, registered_rules

SEVERITIES = ["low", "medium", "high", "critical"]


def rule_param_schemas() -> dict[str, dict[str, Any]]:
    """JSON Schema of every registered rule's `params`, keyed by rule id."""
    return {rule_id: rule.Params.model_json_schema() for rule_id, rule in sorted(_rules().items())}


def rules_file_schema() -> dict[str, Any]:
    """JSON Schema (draft 2020-12) of the whole `rules.yaml`."""
    rules = _rules()
    params = rule_param_schemas()
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "GenAI-VMS event rules (config/rules.yaml)",
        "description": "Generated by `python -m events.schema_export` — do not edit by hand.",
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "version": {"const": 1},
            "rules": {
                "type": "object",
                "additionalProperties": False,
                "properties": {rule_id: _rule_block(params[rule_id]) for rule_id in rules},
            },
            "overrides": {
                "type": "array",
                "items": {"oneOf": [_override_variant(r, params[rid]) for rid, r in rules.items()]},
            },
        },
    }


def _rules() -> dict[str, Rule]:
    return dict(sorted(registered_rules().items()))


def _common_settings(params_schema: dict[str, Any]) -> dict[str, Any]:
    return {
        "enabled": {"type": "boolean"},
        "severity": {"enum": SEVERITIES},
        "verify": {"type": "boolean"},
        "params": params_schema,
    }


def _rule_block(params_schema: dict[str, Any]) -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "properties": _common_settings(params_schema),
    }


def _override_variant(rule: Rule, params_schema: dict[str, Any]) -> dict[str, Any]:
    """An `overrides:` entry for one rule. A rule that looks at a zone may be scoped to a
    camera and/or a zone; a camera-wide rule only to a camera. Either way the entry
    must name at least one of them."""
    properties: dict[str, Any] = {
        "rule": {"const": rule.id},
        "camera": {"type": "string"},
        **_common_settings(params_schema),
    }
    if rule.scope == "zone":
        properties["zone"] = {"type": "string"}
        scoped = {"anyOf": [{"required": ["camera"]}, {"required": ["zone"]}]}
    else:
        scoped = {"required": ["camera"]}
    return {
        "type": "object",
        "additionalProperties": False,
        "required": ["rule"],
        "properties": properties,
        **scoped,
    }
