"""Integration test: migration 0004 creates `events.candidates` exactly as the
model declares it, enforces its CHECK constraints, and downgrades cleanly
(P3-D1 AC "migration included"). Run via `make test-int` (needs Docker).
"""

from __future__ import annotations

import asyncio
import os
import uuid
from datetime import UTC, datetime
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import inspect
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine
from testcontainers.community.postgres import PostgresContainer
from vms_db.base import Base
from vms_db.models import Candidate

pytestmark = pytest.mark.integration

VMS_DB_ROOT = Path(__file__).resolve().parents[2]
T0 = datetime(2026, 10, 1, 7, 0, 0, tzinfo=UTC)


def _async_dsn(container: PostgresContainer) -> str:
    return container.get_connection_url().replace("postgresql+psycopg2", "postgresql+asyncpg")


# Synchronous on purpose, like the other migration tests: Alembic's env.py calls
# asyncio.run() itself, which can't nest inside a running event loop.
def test_migration_0004_creates_candidates_as_the_model_declares_it() -> None:
    with PostgresContainer("postgres:16-alpine") as pg:
        dsn = _async_dsn(pg)
        os.environ["VMS_DB_DSN"] = dsn
        try:
            config = Config(str(VMS_DB_ROOT / "alembic.ini"))
            command.upgrade(config, "head")
            created = asyncio.run(_inspect(dsn))
            behaviour = asyncio.run(_check_constraints_behave(dsn))

            command.downgrade(config, "0003")
            after_downgrade = asyncio.run(_inspect(dsn))

            command.upgrade(config, "head")  # re-applying must work
            after_reupgrade = asyncio.run(_inspect(dsn))
        finally:
            os.environ.pop("VMS_DB_DSN", None)

    model = Base.metadata.tables["events.candidates"]
    # Later migrations add their own tables to the `events` schema (0006: correlation_*), so the
    # table is asserted present, not alone.
    assert "candidates" in created["tables"]
    assert created["columns"] == set(model.c.keys())
    assert created["checks"] == {"ck_candidates_status", "ck_candidates_severity"}
    assert created["indexes"] == {i.name for i in model.indexes}
    assert created["pk"] == ["id"]
    # Regression: the autogenerated draft of this migration dropped Alembic's
    # own version table; applying it would have broken every later upgrade.
    assert created["version_table"]

    assert behaviour == {"valid_insert": True, "bad_status": True, "bad_severity": True}

    assert after_downgrade["schema_exists"] is False
    assert after_downgrade["version_table"]
    assert "candidates" in after_reupgrade["tables"]


async def _inspect(dsn: str) -> dict:
    engine = create_async_engine(dsn)
    try:
        async with engine.connect() as conn:

            def work(sync_conn) -> dict:
                insp = inspect(sync_conn)
                schema_exists = "events" in insp.get_schema_names()
                info: dict = {
                    "schema_exists": schema_exists,
                    "version_table": "alembic_version" in insp.get_table_names(schema="public"),
                    "tables": set(),
                }
                if schema_exists:
                    info["tables"] = set(insp.get_table_names(schema="events"))
                    info["columns"] = {
                        c["name"] for c in insp.get_columns("candidates", schema="events")
                    }
                    info["checks"] = {
                        c["name"] for c in insp.get_check_constraints("candidates", schema="events")
                    }
                    info["indexes"] = {
                        i["name"] for i in insp.get_indexes("candidates", schema="events")
                    }
                    info["pk"] = insp.get_pk_constraint("candidates", schema="events")[
                        "constrained_columns"
                    ]
                return info

            return await conn.run_sync(work)
    finally:
        await engine.dispose()


def _candidate(**overrides) -> Candidate:
    fields = {
        "id": uuid.uuid4(),
        "site_id": "rvce-campus",
        "camera_id": "cam01",
        "rule_id": "loitering",
        "event_type": "loitering",
        "severity": "medium",
        "zone_id": "zone01",
        "zone_name": "entrance",
        "track_ids": ["cam01-t7"],
        "segment_ids": ["cam01_20261001T070000Z_000001"],
        "start_ts": T0,
        "end_ts": T0,
        "rule_score": 0.8,
        "status": "open",
        "details": {"dwell_s": 61.5},
    }
    fields.update(overrides)
    return Candidate(**fields)


async def _check_constraints_behave(dsn: str) -> dict:
    engine = create_async_engine(dsn)
    session_factory = async_sessionmaker(engine, expire_on_commit=False)
    result = {"valid_insert": False, "bad_status": False, "bad_severity": False}
    try:
        async with session_factory() as session:
            session.add(_candidate())
            await session.commit()
            result["valid_insert"] = True

        for key, overrides in (
            ("bad_status", {"status": "pending"}),
            ("bad_severity", {"severity": "catastrophic"}),
        ):
            async with session_factory() as session:
                session.add(_candidate(**overrides))
                try:
                    await session.commit()
                except IntegrityError:
                    result[key] = True
    finally:
        await engine.dispose()
    return result
